In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import math as m

In [4]:
df = pd.read_csv("dataset/insurance (1).csv")

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [18]:
df['sex'] = df['sex'].map({'female': 0, 'male': 1})

In [5]:
x = df.drop(columns=['charges'])

y = df['charges']

In [7]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [8]:
len(x_train)

1070

In [9]:
len(x_test)

268

In [10]:
x_train.head()

      age     sex    bmi  children smoker     region
560    46  female  19.95         2     no  northwest
1285   47  female  24.32         0     no  northeast
1142   52  female  24.86         0     no  southeast
969    39  female  34.32         5     no  southeast
486    54  female  21.47         3     no  northwest

In [11]:
from sklearn.preprocessing import OneHotEncoder

In [19]:
encode = OneHotEncoder(sparse_output=False)
cat = x_train[['sex','smoker','region']]

In [20]:
x_new = encode.fit_transform(cat)

In [21]:
print(x_new)

[[1. 0. 1. ... 1. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 1. 0.]
 ...
 [0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 [0. 1. 1. ... 0. 0. 1.]]

In [23]:
x_new.ndim

2

In [24]:
type(x_new)

numpy.ndarray

In [33]:
df_new = pd.DataFrame({
    'northeast':x_new[:,0],
    'northwest':x_new[:,1],
    'southeast':x_new[:,2],
    'southwest':x_new[:,3]
})

In [36]:
x_train = pd.concat([x_train, df_new], axis=1)

1070

In [37]:
from sklearn.linear_model import LinearRegression

In [38]:
model = LinearRegression()

In [39]:
model.fit(x_train, y_train)

ValueError: could not convert string to float: 'female'